import React from 'react';
import './TermsOfService.css';

const TermsOfService = () => {
    return (
        <div className="terms-page">
            <div className="terms-header-section">
                <h1>Terms of Service</h1>
                <div className="terms-meta">
                    <span>📅 Last Updated: December 2025</span>
                </div>
            </div>

            <div className="terms-content-wrapper">
                <section className="terms-intro-card">
                    <p>
                        Welcome to our <strong>Face Expression Detection platform</strong> (“Service”). By accessing or using this website, you agree to the following Terms of Service (“Terms”). If you do not agree, please do not use the Service.
                    </p>
                </section>

                <div className="terms-grid">
                    <section className="terms-card">
                        <h2>📝 1. Description of Service</h2>
                        <p>
                            Our Service provides tools to analyze facial expressions from images or video streams. The Service is currently free to use, but we may introduce paid plans or additional features in the future.
                        </p>
                    </section>

                    <section className="terms-card">
                        <h2>🔞 2. Eligibility</h2>
                        <p>
                            You must be at least 13 years old to use our Service. By using the Service, you confirm that you meet this age requirement and have the right to agree to these Terms.
                        </p>
                    </section>

                    <section className="terms-card">
                        <h2>🚫 3. User Responsibilities</h2>
                        <p>By using the Service, you agree:</p>
                        <ul>
                            <li>Not to upload harmful, illegal, or copyrighted content without permission.</li>
                            <li>Not to use the Service to identify, harass, discriminate, or harm individuals.</li>
                            <li>Not to misuse, reverse engineer, or attempt to disrupt the platform.</li>
                            <li>To only upload faces or images for which you have proper rights or consent.</li>
                        </ul>
                        <p>You are responsible for how you use the detection results and any decisions based on them.</p>
                    </section>

                    <section className="terms-card">
                        <h2>🔒 4. Privacy & Data Usage</h2>
                        <p>
                            We may temporarily process your uploaded images/videos to analyze facial expressions. We do not sell your data. Uploaded files may be stored temporarily for processing but are not publicly visible.
                        </p>
                        <p>
                            We may use anonymous analytics data to improve the Service. Please review our <a href="/privacy">Privacy Policy</a> for more details.
                        </p>
                    </section>

                    <section className="terms-card">
                        <h2>⚠️ 5. Accuracy Disclaimer</h2>
                        <p>Our face expression detection results are generated by automated algorithms. We do not guarantee:</p>
                        <ul>
                            <li>100% accuracy</li>
                            <li>Real-time correctness</li>
                            <li>Suitability for sensitive or critical decisions</li>
                        </ul>
                        <p>Use the results at your own discretion.</p>
                    </section>

                    <section className="terms-card">
                        <h2>🧠 6. Intellectual Property</h2>
                        <p>
                            All algorithms, code, design assets, trademarks, and branding belong to us. You may use the Service but may not copy, resell, or redistribute it without permission.
                        </p>
                    </section>

                    <section className="terms-card">
                        <h2>🔄 7. Availability & Modification</h2>
                        <p>
                            We may update, improve, or discontinue parts of the Service at any time without prior notice. Since the Service is free, we are not liable for:
                        </p>
                        <ul>
                            <li>Downtime</li>
                            <li>Errors</li>
                            <li>Loss of data</li>
                            <li>Feature changes</li>
                        </ul>
                    </section>

                    <section className="terms-card">
                        <h2>⚖️ 8. Limitation of Liability</h2>
                        <p>To the maximum extent permitted by law:</p>
                        <ul>
                            <li>We are not liable for any damages resulting from the use or inability to use the Service.</li>
                            <li>The Service is provided “as is” and “as available.”</li>
                            <li>You use the platform at your own risk.</li>
                        </ul>
                    </section>

                    <section className="terms-card">
                        <h2>🛑 9. Termination</h2>
                        <p>
                            We may suspend or terminate your access if we detect misuse, abuse, or violation of these Terms. You may stop using the Service at any time.
                        </p>
                    </section>

                    <section className="terms-card">
                        <h2>📅 10. Future Changes</h2>
                        <p>
                            We may update these Terms from time to time. Changes will be posted on this page, and continued use of the Service means you accept the updated Terms.
                        </p>
                    </section>

                    <section className="terms-card contact-card">
                        <h2>📧 11. Contact</h2>
                        <p>For questions, suggestions, or concerns:</p>
                        <div className="contact-box">
                            <p><strong>Email:</strong> <a href="mailto:dheerajsaini131652@gmail.com">dheerajsaini131652@gmail.com</a></p>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    );
};

export default TermsOfService;
